add_newline = false
format = "$custom$directory$git_branch$git_status$character"

[custom.machine]
command = "$HOME/github/dotfiles/bin/prompt-host"
when = "true"
format = "[$output]($style) "
style = "bold cyan"

[directory]
format = "[$path]($style) "
style = "bold green"
truncation_length = 3
truncation_symbol = "../"
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold blue"
symbol = "git:"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "bold red"

[character]
success_symbol = "[\\$](bold green) "
error_symbol = "[\\$](bold red) "
